#! /usr/bin/env sh

HOSTNAME=$(hostname -s)
SCRIPTDIR=$(cd `dirname $0` && pwd)
SCRIPT=$SCRIPTDIR/`basename $0`
ZSHRC=~/.zshrc

if [ -s $ZSHRC ]
then
    echo "You have an existing $ZSHRC file, please remove it and rerun the install to create a new version"
    exit 1
else
    echo "Creating $ZSHRC file"

    INSTALL_TO=$ZSHRC

    cat <<Endmarker > $INSTALL_TO
#
# Generated by $SCRIPT
#

function() {
    local ZSHSETUP=$SCRIPTDIR
    local HOSTNAME=\$(hostname -s)

    source \$ZSHSETUP/zshrc_general

    if [ -s \$ZSHSETUP/\$HOSTNAME/zshrc_plugins ]
    then
        echo "Loading zshrc_plugins for host \$HOSTNAME"
        source \$ZSHSETUP/\$HOSTNAME/zshrc_plugins
    fi

    source \$ZSH/oh-my-zsh.sh

    source \$ZSHSETUP/zshrc_custom

    if [ -s \$ZSHSETUP/\$HOSTNAME/zshrc ]
    then
        echo "Loading zshrc for host \$HOSTNAME"
        source \$ZSHSETUP/\$HOSTNAME/zshrc
    else
        echo "Create a file at \$ZSHSETUP/\$HOSTNAME/zshrc to hold any host specific settings"
    fi

    source \$ZSHSETUP/zshrc_final
}

#
# Anything below here was not added by the install script and could be lost
# if you regenerate this file.
#
Endmarker

    echo "Done creating $ZSHRC file that expects zsh script in $SCRIPTDIR"
fi
